AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an FSx ONTAP file system

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Security Group Configuration
      Parameters:
        - FSxSecurityGroupVpcId
        - FSxSecurityGroupCidrBlock
        - FSxSecurityGroupName
      ParameterLabels:
        FSxSecurityGroupVpcId:
          default: VPC
        FSxSecurityGroupCidrBlock:
          default: CidrBlock
        FSxSecurityGroupName:
          default: Security Group Name
    - Label:
        default: File System Configuration
      Parameters:
        - FSxFileSystemName
        - FSxFileSystemKmsKeyId
        - FSxFileSystemStorageCapacity
        - FSxFileSystemDeploymentType
        - FSxFileSystemSubnetIds
        - FSxFileSystemDeploymentType
        - FSxFileSystemFsxAdminPassword
        - FSxFileSystemPreferredSubnetId
        - FSxFileSystemThroughputCapacity
        - FSxFileSystemDiskIopsConfigurationMode
        - FSxFileSystemAutomaticBackupRetentionDays
    - Label:
        default: Storage Virtual Machine Configuration
      Parameters:
        - SvmName
        - SvmAdminPassword
      ParameterLabels:
        SvmName:
          default: SVM Name
        SvmAdminPassword:
          default: SVM Admin Password
Parameters:
  FSxSecurityGroupVpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of an existing Virtual Private Cloud (VPC).
  FSxSecurityGroupCidrBlock:
    Type: String
    Description: Cidr block for security group  rules
  FSxSecurityGroupName:
    Type: String
    Description: Name of the security group
    Default: fsx-security-group
  FSxFileSystemName:
    Type: String
    Description: The name of the file system
    Default: Fill name
  FSxFileSystemStorageCapacity:
    Type: Number
    Description: Sets the storage capacity of the file system that you're creating. StorageCapacity is required if you are creating a new file system.
    Default: 1024
  FSxFileSystemSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Specifies the IDs of the subnets that the file system will be accessible from
  FSxFileSystemDeploymentType:
    Type: String
    Description: Specifies the FSx for ONTAP file system deployment type to use in creating the file system.
    AllowedValues:
      - MULTI_AZ_1
      - MULTI_AZ_2
      - SINGLE_AZ_1
      - SINGLE_AZ_2
    Default: SINGLE_AZ_2
  FSxFileSystemKmsKeyId:
    Type: String
    Description: KMS Key ID
  FSxFileSystemFsxAdminPassword:
    Type: String
    Description: The ONTAP administrative password for the fsxadmin user with which you administer your file system using the NetApp ONTAP CLI and REST API
    Default: Fill FSx Admin password
  FSxFileSystemPreferredSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Required when DeploymentType is set to MULTI_AZ_1. This specifies the subnet in which you want the preferred file server to be located
  FSxFileSystemThroughputCapacity:
    Type: String
    Description: Sets the throughput capacity for the file system that you're creating in megabytes per second (MBps)
    Default: 384
  FSxFileSystemDiskIopsConfigurationMode:
    Type: String
    AllowedValues:
      - AUTOMATIC
      - USER_PROVISIONED
    Description: Specifies whether the file system is using the AUTOMATIC setting of SSD IOPS of 3 IOPS per GB of storage capacity, or if it using a USER_PROVISIONED value
    Default: AUTOMATIC
  FSxFileSystemAutomaticBackupRetentionDays:
    Type: Number
    Description: The number of days to retain automatic backups. Setting this property to 0 disables automatic backups.
    Default: 30
  SvmName:
    Type: String
    Description: The name of the SVM.
    Default: 

Resources:
  FSxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: FSxN Cloud firewall rules for management and data interface
      VpcId:
        Ref: FSxSecurityGroupVpcId
      GroupName:
        Ref: FSxSecurityGroupName
      SecurityGroupIngress:
      - FromPort: -1
        ToPort: -1
        IpProtocol: icmp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 22
        ToPort: 22
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 80
        ToPort: 80
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 111
        ToPort: 111
        IpProtocol: udp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 111
        ToPort: 111
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 139
        ToPort: 139
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 161
        ToPort: 162
        IpProtocol: udp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 161
        ToPort: 162
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 443
        ToPort: 443
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 445
        ToPort: 445
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 635
        ToPort: 635
        IpProtocol: udp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 635
        ToPort: 635
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 749
        ToPort: 749
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 2049
        ToPort: 2049
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 2049
        ToPort: 2049
        IpProtocol: udp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 3260
        ToPort: 3260
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 4045
        ToPort: 4046
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 4045
        ToPort: 4046
        IpProtocol: udp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 4049
        ToPort: 4049
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 10000
        ToPort: 10000
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      - FromPort: 11104
        ToPort: 11105
        IpProtocol: tcp
        CidrIp:
          Ref: FSxSecurityGroupCidrBlock
      SecurityGroupEgress:
      - Description: Allow all outbound traffic
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
  FSxFileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: ONTAP
      KmsKeyId:
        Ref: FSxFileSystemKmsKeyId
      SecurityGroupIds:
        - Fn::GetAtt:
          - FSxSecurityGroup
          - GroupId
      OntapConfiguration:
        AutomaticBackupRetentionDays:
          Ref: FSxFileSystemAutomaticBackupRetentionDays
        DeploymentType:
          Ref: FSxFileSystemDeploymentType
        DiskIopsConfiguration:
          Mode:
            Ref: FSxFileSystemDiskIopsConfigurationMode
        FsxAdminPassword:
          Ref: FSxFileSystemFsxAdminPassword
        PreferredSubnetId:
          Ref: FSxFileSystemPreferredSubnetId
        ThroughputCapacity:
          Ref: FSxFileSystemThroughputCapacity
      StorageCapacity:
        Ref: FSxFileSystemStorageCapacity
      SubnetIds:
        Ref: FSxFileSystemSubnetIds
      Tags:
        - Key: Name
          Value:
            Ref: FSxFileSystemName
  StorageVirtualMachine:
    Type: AWS::FSx::StorageVirtualMachine
    Properties:
      FileSystemId:
        Ref: FSxFileSystem
      Name:
        Ref: SvmName