import * as vscode from 'vscode';
import { FileSystemMetrics, VolumeMetrics } from './FileSystemApis';
import { state } from './state';
import { copilot_question } from './telemetryReporter';
import { getModel } from './chat/modelFactory';
import { Logger, LogLevel } from './logger';
import { getAllTools, AskUserError } from './chat/tools';

const SYSTEM_PROMPT = `You are an AWS FSx for NetApp ONTAP expert assistant integrated into VS Code.

You help users understand and manage their FSx ONTAP filesystems, volumes, SVMs, backups, and performance metrics.

You have access to tools that let you query the user's AWS account in real time. Use them to answer questions accurately.
Do NOT guess or make up data — always call the appropriate tool to get current information.

Guidelines:
- If the question is not about AWS FSx ONTAP, say you can only answer questions related to AWS FSx ONTAP.
- You can identify a filesystem by its ID (fs-...) or by its Name tag.
- When questions involve multiple entities, gather all relevant data before answering.
- For ONTAP-level details not available through the AWS APIs (e.g., aggregates, network interfaces, snapmirror, export policies, qtrees, quotas), use the run_ontap_cli tool.
- For CloudWatch metrics, use the get_cloudwatch_metrics tool. Available filesystem metrics: ${FileSystemMetrics.join(', ')}. Available volume metrics: ${VolumeMetrics.join(', ')}.
- For shell commands or AWS CLI operations, use the run_terminal_command tool.
- When the user's question is ambiguous or you need them to choose between multiple options, use the ask_user tool to present choices. For example, if the user asks about "my filesystem" but has multiple filesystems, ask them to pick one.
- Present your answers clearly with markdown formatting.
- End your response with a disclaimer that the analysis was generated by AI.

The user's currently selected AWS regions are: ${state.getSelectedRegions().join(', ')}.`;

export interface FollowupMetadata {
    question: string;
    options: Array<{ label: string; value: string }>;
}

export async function handleChatRequest(
	request: vscode.ChatRequest,
	context: vscode.ChatContext,
	stream: vscode.ChatResponseStream,
	token: vscode.CancellationToken
): Promise<vscode.ChatResult> {
    try {
        const model = await getModel(token);

        if (model.type !== 'copilot') {
            stream.markdown(`\nUsing AI model: ${model.type}\n`);
        }

        state.reporter.sendTelemetryEvent(copilot_question, { prompt: request.prompt, type: model.type });
        stream.progress('Processing request...');

        const tools = getAllTools();

        let userMessage = request.prompt;
        if (request.command === 'filesystem') {
            userMessage = `[Context: The user is asking about a specific filesystem and may need ONTAP CLI-level details. Use the run_ontap_cli tool if the AWS APIs don't have the information needed. First use get_filesystems to identify the filesystem.]\n\n${request.prompt}`;
        }

        const result = await model.sendMessageWithTools(
            SYSTEM_PROMPT,
            userMessage,
            tools,
            stream,
            token
        );

        stream.markdown('\n');
        stream.markdown(result);
        stream.markdown('\n');
        return {};
    } catch (error) {
        if (error instanceof AskUserError) {
            stream.markdown(`\n**${error.question}**\n\n`);
            stream.markdown('Please select one of the options below:\n\n');
            for (const option of error.options) {
                stream.markdown(`- ${option.label}\n`);
            }
            return {
                metadata: {
                    followups: {
                        question: error.question,
                        options: error.options
                    } satisfies FollowupMetadata
                }
            };
        }

        Logger.log('Error handling chat request.', LogLevel.Error, error as Error);
        stream.markdown(`Failed to process chat request with error: ${error instanceof Error ? error.message : 'Unknown error'}`);
        return {};
    }
}
